"""empty message

Revision ID: 086adfb5bdd6
Revises: 1b797d217897
Create Date: 2025-11-03 18:57:10.145733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '086adfb5bdd6'
down_revision = '1b797d217897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: The `title` column on `goal` already exists in the target
    # database (it was created outside of this migration history). To
    # avoid attempting to re-create it (which would raise a DuplicateColumn
    # error), skip adding the column here.
    #
    # Also avoid altering the `id` identity/serial column on `task`; such
    # server-default/identity changes can produce invalid SQL (DROP DEFAULT)
    # for Postgres IDENTITY columns. Leave identity handling untouched.

    # ### end Alembic commands ###
    # nothing to run in this migration (changes were already applied)
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Downgrade: nothing to do here for `task.id` or `goal.title` because
    # we did not make any changes in upgrade().

    # ### end Alembic commands ###
    # nothing to undo
    pass
