"""empty message

Revision ID: 31be11685a24
Revises: 
Create Date: 2025-11-01 18:20:16.993960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31be11685a24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('planet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('completed_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='planet_pkey')
    )
    op.drop_table('task')
    op.drop_table('goal')
    # ### end Alembic commands ###
